# Generated by Django 5.1 on 2024-08-08 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialTracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time_in", models.TimeField(default=django.utils.timezone.now)),
                ("time_out", models.TimeField(default=django.utils.timezone.now)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materialTracker.worker",
                    ),
                ),
            ],
        ),
    ]
