# Generated by Django 4.2.2 on 2024-08-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialTracker", "0004_materialusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
