# Generated by Django 4.2.2 on 2024-08-15 10:46

from django.db import migrations, models
import django.utils.timezone
import materialTracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("materialTracker", "0006_material_quantity_alter_material_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[materialTracker.models.validate_not_future_date],
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="date_purchased",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[materialTracker.models.validate_not_future_date],
            ),
        ),
        migrations.AlterField(
            model_name="materialusage",
            name="date_used",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[materialTracker.models.validate_not_future_date],
            ),
        ),
    ]
