# Generated by Django 4.2.6 on 2024-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "materialTracker",
            "0007_alter_attendance_date_alter_material_date_purchased_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialusage",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
