# Generated by Django 4.2.6 on 2024-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialTracker", "0008_alter_materialusage_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialusage",
            name="quantity",
            field=models.CharField(max_length=10),
        ),
    ]
