# Generated by Django 4.2.6 on 2024-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialTracker", "0010_alter_materialusage_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialusage",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
